trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, it's my Azure DevOps App
  displayName: 'Run an echo command'

- script: |
    set JAVA_HOME=F:\jdk-17.0.12_windows-x64_bin\jdk-17.0.12
    set PATH=%JAVA_HOME%\bin;%PATH%
    java -version
    mvn clean install
  displayName: 'Build with Maven using local Java 17'

- script: |
    echo "Build output path: $(Build.SourcesDirectory)\target"
  displayName: 'Print target path'

- script: |
    set JAVA_HOME=F:\jdk-17.0.12_windows-x64_bin\jdk-17.0.12
    set PATH=%JAVA_HOME%\bin;%PATH%
    echo Running JAR...
    java -jar "$(Build.SourcesDirectory)\target\poornashree-0.0.1-SNAPSHOT.jar"
  displayName: 'Run the built poornashree JAR'
