trigger:
- master

pool:
  name: Default  # Your self-hosted agent pool

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'

- script: java -jar "$(Build.SourcesDirectory)\target\poornashree-0.0.1-SNAPSHOT.jar"
  displayName: 'Run the built JAR'
