trigger:
- master

pool:
  name: Default  # Your self-hosted agent pool

steps:
# Use local Java 17 (already installed on your machine)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Run Gradle build using wrapper (assumes gradlew exists in the root)
- task: Gradle@2
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)/poorna'  # because your root project folder is 'poorna'
    gradleWrapperFile: '$(Build.SourcesDirectory)/poorna/gradlew'
    tasks: 'clean build'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/test/*.xml'

# Run the built JAR
- script: java -jar "$(Build.SourcesDirectory)/poorna/app/build/libs/app.jar"
  displayName: 'Run the built JAR'
