trigger:
- master

pool:
  name: Default  # Your self-hosted agent pool

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # Since you're using a local JDK

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'

- script: java -jar "$(Build.SourcesDirectory)\app\build\libs\app.jar"
  displayName: 'Run the built JAR'
